test-frontend:
  stage: test
  script:
    - cd Frontend
    - cd my-app
    - npm install
    - npm run test

test-backend:
  stage: test
  script:
    - cd Backend
    - npm install 
    - npm run test

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."