test-frontend:
  stage: test
  script:
    - cd Frontend
    - cd my-app
    - npm install
    - npm run test
  allow_failure: true

test-backend:
  stage: test
  script:
    - cd Backend
    - npm install 
    - npm run test
  allow_failure: true

#deploy-frontend-prod:
 # only:
 #   - master
  #stage: deploy
  #script:
    #- cd Frontend
    #- cd my-app 
    #- npm install
    #- lsof -ti tcp:3000 | xargs kill
    #- ( npm run start </dev/null &>/dev/null & )
    #- echo "server ran start script\n"
    #- exit 0
#deploy-backend-prod:
#  only:
#    - master
#  stage: deploy
#  script:
#    - cd Backend 
#    - npm install
#    - lsof -ti tcp:8000 | xargs kill
#    - ( npm run start </dev/null &>/dev/null & )
#    - echo "backend server before script has ran\n"
#    - exit 0